exports_files(["gtkwave.tcl.template"])

py_binary(
    name = "gtkwave_wrapper",
    srcs = ["gtkwave_wrapper.py"],
    visibility = ["//visibility:public"],
)

py_binary(
    name = "symbiyosys_wrapper",
    srcs = ["symbiyosys_wrapper.py"],
    visibility = ["//visibility:public"],
)
